### ISSUE TITLE
「京大」去年の学生データベースをアックスできますか？

### ISSUE THREAD

**Issue by duydl** [kyoto-u/openpanda#237]
学生は去年のグループから外されてしまいました。しかし、復習のため私はちゃんとアーカイブしなかった去年の授業の資料や宿題の先生のコメントを回復したいと思います。先生から聞くと毎年前年の学生データベースが更新されるそうです。つまり、去年の学生データベースをアックスできなくなりましたか？
また、学生が前年のPandaグループに留まることを許可することは可能ですか？

**Comment by tkoichiro** [comment]
ここはPandAの技術的なソースコードのためのレポジトリです。こちらでご質問することはおやめ下さい。
質問に関しては www.iimc.kyoto-u.ac.jp のお問い合わせからお願いします。
