### ISSUE TITLE
外部カレンダーサービスとの連携

### ISSUE THREAD

**Issue by naoki9911** [kyoto-u/openpanda#239]
課題等の締め切りを Google カレンダー等のカレンダーサービスに自動で登録する機能が欲しいです。

**Comment by shojikajita** [comment]
Sakai には以下の機能がありますが，enable になっています:

**Comment by shojikajita** [comment]
PandA → Google Calendar へのフィードであれば，Calendar → Publish で公開できると思います．

**Comment by shojikajita** [comment]
課題の締切日時については，担当教員次第ですが，各サイトで課題作成時に「締切日時をカレンダに追加」を選択すると追加されます．
