### ISSUE TITLE
課題ツールで再提出を許可した場合の通知メールが英語になる

### ISSUE THREAD

**Issue by sndtkrh** [kyoto-u/openpanda#80]
課題ツールで課題作成時に「再提出を許可」のチェックボックスを入れて
「成績公開時や再提出受付開始時に通知メールを受講者に送信」にチェックする．
![2017-11-14 15 02 22](https://user-images.githubusercontent.com/5213322/32765504-141f4054-c94e-11e7-956d-b51eac4b08fe.png)
この状態で課題を採点して返却すると受講者に通知メールが送られてくる．
このメールが英語のままになっている．

例
メールタイトル: 「Assignment submission has been corrected」
内容「
サイトタイトル: PandA OA Test2
サイト ID: 8030533e-63be-41bf-9ed6-3a5d3574a461

Your submission to assignment "課題のテスト" has been corrected and it allows resubmissions until the due date. Please go to PandA OA Test2 to view details.
」

**Comment by skanae** [comment]
sakai/assignment/bundles/resources/assignment.propertiesのところに
noti.releaseresubmission.text=Your submission to assignment "{0}" has been graded and it allows resubmissions until the due date. Please go to {1} to view details.
がありました。
これの日本語versionのsakai/assignment/bundles/resources/assignment_ja.propertiesを確認したところちゃんと翻訳されていました。
noti.releaseresubmission.textが日本語の方に参照されていないようです。

**Comment by tkoichiro** [comment]
openpanda 側は問題ありませんでした。
運用中の panda で assignment_ja.properties の日本語が英文になっていませんでした。
