### ISSUE TITLE
サイト担当者が課題提出の通知を一日ごとに送信するようにした場合の日本語が不自然

### ISSUE THREAD

**Issue by sndtkrh** [kyoto-u/openpanda#81]
「次の通知ダイジェスト」となっているが，「次の」は不要
![2017-11-21 14 04 35](https://user-images.githubusercontent.com/5213322/33055782-fc108d66-cec4-11e7-8816-109ad61397c6.png)

**Comment by skanae** [comment]
/config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/emailimpl/email-impl_ja.properties
のところに”次の通知ダイジェスト：”をunicode escapeに変換された

notif=\u6b21\u306e\u901a\u77e5\u30c0\u30a4\u30b8\u30a7\u30b9\u30c8\uff1a

を発見しました。

\u6b21\u306e  

という部分が”次の”に相当するコードです。
